In [18]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import warnings
warnings.filterwarnings('ignore')

In [32]:
df = pd.read_csv("multipleLRhomeprices.csv")
print(df)

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000


In [35]:
# Handling missing data
med = df.bedrooms.median()
df.bedrooms = df.bedrooms.fillna(med)

In [36]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [37]:
model = linear_model.LinearRegression()

In [38]:
model.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [41]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [42]:
model.intercept_

221323.0018654043

In [45]:
model.predict([[4000, 5, 15]])

array([738041.40139414])

In [ ]:
y = m1 * area + m2 * bedrooms + m3 * age + c

In [46]:
 y = 112.06244194 * 4000 + 23388.88007794 *  5  -3231.71790863 * 15 + 221323.0018654043

In [47]:
y

738041.4013856543

In [48]:
# Prediction
model.predict([[4500, 5, 15]])

array([794072.62236521])